openapi: 3.0.3
info:
  title: ZKorum
  description: ZKorum backend
  version: 1.0.0
components:
  schemas: {}
paths:
  /auth/isEmailAvailable:
    put:
      requestBody:
        content:
          application/json:
            schema:
              type: string
              format: email
              maxLength: 254
              minLength: 1
              description: Email address
        description: Email address
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: boolean
  /auth/register:
    put:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  maxLength: 254
                  minLength: 1
                  description: Email address
                didExchange:
                  type: string
                  maxLength: 1000
                  description: Decentralized Identifier with did:key method
              required:
                - email
                - didExchange
              additionalProperties: false
        required: true
      responses:
        "200":
          description: Default Response
servers: []
