openapi: 3.0.3
info:
  title: ZKorum
  description: ZKorum backend
  version: 1.0.0
components:
  schemas: {}
paths:
  /auth/getUserId:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: string
              format: email
              maxLength: 254
              minLength: 1
              description: Email address
        description: Email address
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
                format: uuid
                minLength: 1
  /auth/authenticate:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  maxLength: 254
                  minLength: 1
                  description: Email address
                userId:
                  type: string
                  format: uuid
                  minLength: 1
                didExchange:
                  type: string
                  maxLength: 1000
                  description: Decentralized Identifier with did:key method
              required:
                - email
                - userId
                - didExchange
              additionalProperties: false
        required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  codeId:
                    type: integer
                    minimum: 0
                  codeExpiry:
                    type: string
                    format: date-time
                required:
                  - codeId
                  - codeExpiry
                additionalProperties: false
  /auth/validateOtp:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                  maxLength: 6
                  minLength: 1
                codeId:
                  type: integer
                  minimum: 0
              required:
                - code
                - codeId
              additionalProperties: false
        required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: boolean
servers: []
