openapi: 3.0.3
info:
  title: ZKorum
  description: ZKorum backend
  version: 1.0.0
components:
  schemas: {}
paths:
  /auth/getUserId:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: string
              format: email
              maxLength: 254
              minLength: 1
              description: Email address
        description: Email address
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
                format: uuid
                minLength: 1
  /auth/authenticate:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  maxLength: 254
                  minLength: 1
                  description: Email address
                userId:
                  type: string
                  format: uuid
                  minLength: 1
                didExchange:
                  type: string
                  maxLength: 1000
                  description: Decentralized Identifier with did:key method
              required:
                - email
                - userId
                - didExchange
              additionalProperties: false
        required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  codeExpiry:
                    type: string
                    format: date-time
                required:
                  - codeExpiry
                additionalProperties: false
  /auth/validateOtp:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: number
                  minimum: 0
                  maximum: 999999
              required:
                - code
              additionalProperties: false
        required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                anyOf:
                  - type: object
                    properties:
                      success:
                        type: boolean
                        enum:
                          - true
                    required:
                      - success
                    additionalProperties: false
                  - type: object
                    properties:
                      success:
                        type: boolean
                        enum:
                          - false
                      reason:
                        type: string
                        enum:
                          - expired_code
                          - wrong_guess
                    required:
                      - success
                      - reason
                    additionalProperties: false
servers: []
